importScripts(
  'src/background/constants.js',
  'src/background/runtime.js',
  'src/background/settings.js',
  'src/background/debug.js',
  'src/background/logging.js',
  'src/background/sites.js',
  'src/background/analysis.js',
  'src/background/prompt.js',
  'src/background/lm-studio.js',
  'src/background/stats.js',
  'src/background/errors.js'
);
